### ISSUE TITLE
[URITokenMint with Amount:"0" does not reflect in meta data] (Version: 2023.10.30-release+443])

### ISSUE THREAD

**Issue by nixer89** [Xahau/xahaud#209]
When someone mints a new URIToken with `Amount:"0"` and a `Destination` set, the `Amount` field is missing in the meta data on the newly created `URIToken` ledger object.

Example transaction:

D636ABADC71096929861F24261210F17A8BD8505A24AF74F614C9057D7C83B42

```
{
	"CreatedNode": {
		"LedgerEntryType": "URIToken",
		"LedgerIndex": "39C0D52EDEF285103DF8A9CCE6F4E1A4AE206A76D46BA2AF4834135856E36840",
		"NewFields": {
			"Destination": "rnBA8kVE8ZxqiRnUccKEo2x1Qa6sJWDXA9",
			"Issuer": "rHyB8fpHCTB4NhwayEtNH9DsjLue33n1ph",
			"Owner": "rHyB8fpHCTB4NhwayEtNH9DsjLue33n1ph",
			"URI": "697066733A2F2F516D503944734D356A6B6B68615466694853774741456E316557323263586546734D41715A5A424C48735A726976"
		}
	}
},
```

**Comment by RichardAH** [comment]
https://github.com/Xahau/xahaud/blob/4cb93f943b7af675f4df8e9be831ee2ccce41da5/src/ripple/ledger/impl/ApplyStateTable.cpp#L235-L239

**Comment by dangell7** [comment]
https://github.com/Xahau/xahaud/blob/4cb93f943b7af675f4df8e9be831ee2ccce41da5/src/ripple/protocol/impl/STAmount.cpp#L682

**Comment by Silkjaer** [comment]
This fix should also be ported to [rippled](https://github.com/xrplf/rippled) with example NFTokenOfferCreate https://bithomp.com/explorer/FBD48E8D240B5F7B6883B448437F000BDD998489660FEBA6257EE2F7A55DEAFF not showing the Amount "0" in the metadata for NFTokenOffer EB4FD457B81ED0510FCCAF86D935B26D9380DFEF7D12AAC4D447E0DD2C3961D8

**Comment by RichardAH** [comment]
https://github.com/Xahau/xahaud/tree/meta-fix

**Comment by RichardAH** [comment]
https://github.com/Xahau/xahaud/pull/231
