### ISSUE TITLE
Allow to get DeployFee, maxInstrCountHook, maxInstrCountCbak of Hook from Fee command.

### ISSUE THREAD

**Issue by tequdev** [Xahau/xahaud#283]
DeployFee can be calculated from the size of the compiled wasm file, but ExecutionFee requires the creation of a HookDefinition object in the test/local environment, etc.

**Comment by RichardAH** [comment]
If you checkout the repo and go into src/ripple/app/hooks/ there's a standalone program called "guard checker" which will produce this information for you from the commandline
https://github.com/Xahau/xahaud/blob/dev/src/ripple/app/hook/makefile
