### ISSUE TITLE
Add "B2M to zero" amendment

### ISSUE THREAD

**Issue by WietseWind** [Xahau/xahaud#290]
B2M was originally added to Xahau to provide a way for people to obtain the native asset without the need for a secondary market, without the need for an actively operated bridge, etc.

While B2M works really well and has a slow decline to yielding 0 on the mint side, there will be a point in time where there is sufficient availability of secondary markets to obtain XAH. There may be a point in time where regulatory changes / additions change the implications of minting new assets through what may be explained as a bridge of sorts (which one can argue it isn't, but...)

I'd like to propose an amendment - so it can be voted in if ever deemed sensible or necessary, to immediately (post amendment activation) reduce the B2M yield to 0 (as if we're at the end of the B2M timeline). 

This will keep several aspects in place, like the account activation flow & regular key/signer list sync, but it'll just not yield any XAH for XRP burned on mainnet.

**Comment by RichardAH** [comment]
merged
