### ISSUE TITLE
Include Flags in Server Definitions

### ISSUE THREAD

**Issue by WietseWind** [Xahau/xahaud#303]
With different amendments not only come different TX types and fields, but also different flags. As we see right now, even the same flag numbers with different meanings. For example, `AccountSet` flag 16 on XRPL mainnet is `asfAllowTrustLineClawback` while on Xahau `asfDisallowIncomingRemit`.

- https://github.com/Xahau/xahaud/blob/88308126ccf5eb1d15010e790c810f1548158832/src/ripple/protocol/TxFlags.h#L88
  <img width="607" alt="image" src="https://github.com/Xahau/xahaud/assets/4756161/7a216d50-12b8-45ff-9bc9-aa078847d15f">

- https://github.com/XRPLF/rippled/blob/4bcbf70cae6dc4883c4e695e25a90267b32effa4/src/ripple/protocol/TxFlags.h#L90
  <img width="602" alt="image" src="https://github.com/Xahau/xahaud/assets/4756161/34add085-8e8a-433a-90bf-3c9f265c003b">

I propose the flags are included in the RPC `server_definitions` calls, so explorers & clients like Xaman can adapt ther screens (e.g. Sign Request & TX Details information) to a specific network.

I propose an object added to the definitions with an array with e.g. Flags per TX Type, or even an object with TX Type » Flag » integer. (Or any other format).

```
[
  { transactor: 'AccountSet', flagName: 'asfAllowTrustLineClawback', flag: 16 }
]
```

or

```
{
  AccountSet: {
    asfAllowTrustLineClawback: 16
  }
}

```

# Prio

This is needed for:
- https://github.com/XRPL-Labs/Xaman-Issue-Tracker/issues/492

**Comment by RichardAH** [comment]
yep good catch, we'll add to server definitions

**Comment by zgrguric** [comment]
I would like to see flags included on XRPL also.

**Comment by WietseWind** [comment]
> I would like to see flags included on XRPL also.

Yep we should definitely PR this into xrplf/rippled

**Comment by WietseWind** [comment]
@N3TC4T This will be in the upcoming xahaud release :) So we can include the right flag names in 3.0 :)

**Comment by RichardAH** [comment]
https://github.com/Xahau/xahaud/pull/304
https://github.com/Xahau/xahaud/pull/306
