### ISSUE TITLE
Request: more verbose logging on QuickJS error/crash

### ISSUE THREAD

**Issue by WietseWind** [Xahau/xahaud#324]
Currently, when QuickJS gives up (JS error), the entire engine is dead and new JS Hooks won't be executed.

It would help if:

- In trace logging, the JS error from QUICKJS is displayed @ logging as well
Right now all I can see in the trace log is:

```
Could not create QUICKJS instance (expr eval failure). `Hook(0)` [size=7]. [function bytecode]
```

When I wrap the entire hook in a Try Catch I see the underlying error:
```
  try {
    const v = yolo()
  } catch (e) {
    trace('err', e.message, false)
  }
```

Yields:
```
err: "'yolo' is not defined"
```

If not possible to get to this underlying error for trace, we could consider wrapping all Hooks in a try / catch (?)

Question then would be what to do: reject or accept :X

**Comment by RichardAH** [comment]
https://github.com/Xahau/xahaud/commit/9db9ad2123c30755ac9c5c53a8a4359dc5330fa2

**Comment by RichardAH** [comment]
Play around with this change, I think it should do for most jsvm logging. If not let me know.

**Comment by WietseWind** [comment]
Working like a charm :) Thanks!

**Comment by tequdev** [comment]
What about passing the error message to rollback if an Error is thrown?
