### ISSUE TITLE
Promises: to be disabled?

### ISSUE THREAD

**Issue by WietseWind** [Xahau/xahaud#331]
https://github.com/Xahau/xahaud/blob/jshooks/src/ripple/app/hook/applyHook.h#L1314

^^ 
```
JS_AddIntrinsicPromise(ctx);
```

... Shouldn't promises be disabled @ HooksJS?

**Comment by RichardAH** [comment]
good one

https://github.com/Xahau/xahaud/commit/f2becaf140a2457d8b1c36badf2ce50153b14c70
