### ISSUE TITLE
Certain String functions not available

### ISSUE THREAD

**Issue by WietseWind** [Xahau/xahaud#337]
String fns like:
`somestring'.slice(0, 4)`

**Comment by tequdev** [comment]
works for me.

`trace("TRC", 'somestring'.slice(0, 4), false)`
`TRC: "some"`

**Comment by WietseWind** [comment]
Never mind, with stupid again :( String function on a non string 🤦

**Comment by WietseWind** [comment]
Edit: I really need more verbose error information @ trace log from QuickJS engine 😂
