### ISSUE TITLE
C cpecific errors were removed durning refactor. 

### ISSUE THREAD

**Issue by dangell7** [Xahau/xahaud#341]
During refactor of the hook_api some of the c specific errors were removed. 

`TOO_BIG`, `TOO_SMALL`, `OUT_OF_BOUNDS`, etc. 

- `foreign_state_set`
- `foreign_state`
- `state`
- `state_set`

> Tests on SetHook are currently failing so the issue is reproducible.

**Comment by RichardAH** [comment]
Ah that's a problem. Don't change the tests to match, can you find where the tests are failing and add code to maintain the same original C behaviour please?

**Comment by dangell7** [comment]
> Ah that's a problem. Don't change the tests to match, can you find where the tests are failing and add code to maintain the same original C behaviour please?

Yes exactly, I will use the failing tests to add back in the correct errors. The `SetHook_test` file must remain unchanged and passing with this merge.

**Comment by dangell7** [comment]
https://github.com/Xahau/xahaud/pull/318/commits/c1610a6dda338165c139dfb8948a60a79524d28b
