### ISSUE TITLE
[JSHooks] `slot_float` should return a value of type bigint, not number

### ISSUE THREAD

**Issue by tequdev** [Xahau/xahaud#343]
https://github.com/Xahau/xahaud/blob/a498ebeac49362431bb7be642cb9ff431673f41a/src/ripple/app/hook/impl/applyHook.cpp#L3939-L3954

line 3951 should be
```ts
returnJSXFL(__slot_float(hookCtx, applyCtx, j, *slot_no)); 
```

**Comment by dangell7** [comment]
How does this look?

https://github.com/Xahau/xahaud/pull/318/commits/9e7bee5564486b4cd83407fff1ae38b75104d619

**Comment by tequdev** [comment]
out=0 is not an result error, but a normal value as XFL, so shouldn't it be of type bigint?

so I think it should be this?
```cpp
if (out < 0)
```

**Comment by dangell7** [comment]
Yes you're right.

**Comment by dangell7** [comment]
updated
