### ISSUE TITLE
Merge review: rippled 2.2.2. job queue slot for validation ledger check & inbound validation

### ISSUE THREAD

**Issue by WietseWind** [Xahau/xahaud#357]
Impact & merge need review:

- https://github.com/XRPLF/rippled/commit/fbbea9e6e25795a8a6bd1bf64b780771933a9579
- https://github.com/XRPLF/rippled/commit/774148389467781aca7c01bac90af2fba870570c

**Comment by WietseWind** [comment]
@dangell7 @RichardAH FH nodes seem to do better after this (in terms of transitions & lagging)

**Comment by WietseWind** [comment]
Merging

https://github.com/Xahau/xahaud/tree/merge/2.2.2-jobqueue

---

Built: https://build.xahau.tech/2024.9.5-HEAD%2B968

Now running on the 2 worst performing RPC nodes (load) to compare (RPC12 and RPC16)

**Comment by dangell7** [comment]
https://github.com/Xahau/xahaud/pull/360
